### ISSUE TITLE
Android Marshmallow> permissions are not being requested during run time

### ISSUE THREAD

**Issue by balaabhinav** [bit6/bit6-cordova#10]
Hi,

When I try to run my app in my marshmallow phone, the permissions for camera and microphone are not being requested during run time and It looks like a showstopper for me. Let me know of any fixes or when the fix can be expected? Thanks..

**Comment by agol** [comment]
We are using WebRTC API in Android WebView to access camera. Unfortunately the WebView does not trigger native Android permission requests for camera and mic access. A workaround is to use native code to request the permissions. For example, using this plugin: https://github.com/NeoLSN/cordova-plugin-android-permissions
