### ISSUE TITLE
Front Camera and voice is not working in Video call

### ISSUE THREAD

**Issue by DencerV** [bit6/bit6-cordova#15]
Hi Buddy,

                Actually in some of the phones like lenova vibe k5 the front camera and voice is not coming up in video call.
Thanks

**Comment by agol** [comment]
On some Android devices the WebRTC runtime within the WebView or Chrome browsers is not able to connect to one of the camera devices. The easiest way to test if this issue is in the WebView or Bit6 SDK is to try the official WebRTC web demo in the browser on the device: https://appr.tc/
