### ISSUE TITLE
Compatibility with Cordova-Android 4

### ISSUE THREAD

**Issue by EddyVerbruggen** [bit6/bit6-cordova#3]
Hi,

I was trying the plugin with Cordova-Android 4.0.2 and things didn't compile unfortunately.

The errors are with `PhoneRTCPlugin.java`: `webView.addView` and `webView.removeView` no longer exist :(

**Comment by narek-h** [comment]
hi Eddy, 

thanks for letting us know. 

we are looking on it, and will have that fixed soon. 

Narek

**Comment by narek-h** [comment]
Fixed in 0.9.5 version.
