### ISSUE TITLE
Voice call is not working, the call gets placed but even after “Answer” we are not hearing the voice

### ISSUE THREAD

**Issue by jothikumarm** [bit6/bit6-cordova#4]
Voice call is not working, the call gets placed but even after “Answer” we are not hearing the voice.
Please advise

**Comment by narek-h** [comment]
Hello,

Sorry for the late reply.

I was able to reproduce the issue with voice calls (calling party does not hear the voice from the peer). 

We'll investigate the issue and hopefully will have a fix soon. The fix will be included into the coming release. 

In case we have a workaround (or quick fix) I'll let you know asap (before the release).

Thanks for reporting this.

```
   Narek  
```

**Comment by narek-h** [comment]
Hello, 

the current version (0.9.6) should have this fixed.  Could you please let us know if it's working ok on your side ? 

Thanks,
   Narek
