### ISSUE TITLE
Missing 64 bit support

### ISSUE THREAD

**Issue by hharyanto** [bit6/bit6-cordova#5]
Beginning February 1st 2015 new iOS app submitted to the App Store must include 64-bit support and be built with the iOS 8 SDK.

Is there any 64 bit support for this plugin?

**Comment by narek-h** [comment]
Hello, 

0.9.6 version has 64bit support for iOS.  

Please let us know if you see any issue. 

I think this issue can be closed. 

 Thanks,
     Narek
