### ISSUE TITLE
Appgyver support

### ISSUE THREAD

**Issue by gaj-rscpp** [bit6/bit6-cordova#6]
Hi, 
I am trying to use this pluigin for an app i am making using appgyver which is built on top of cordova. all the the cordova plugins i tried work on appgyver except this. I get "Failed to fetch package information for cordova-plugin-device" when i try to build the app using appgyver cloud services. any help would be amazing :)

**Comment by narek-h** [comment]
Hello, 

thanks for reaching out. 

Actually we haven't tried our plugin on appgyver yet. Will look on this now.

The plugin has a dependency on cordova-plugin-device defined in plugin.xml. I assume this is the cause. Though, the plugin with dependency works just fine using cordova-cli. Probably something gets broken on appgyver side. 

If you have a contact at appgyver with whom we can discuss such issues, would be great if you can share with us. It will speed up the process. 

 Thanks,
   Narek

**Comment by gaj-rscpp** [comment]
Hi Narek,

Thanks for replying so quick. I don't have a contact at appgyver but i have asked the community for support. Hopefully someone will help speed it up. 

I hope this can also shed a bit more lights on how appgyver cloud build world.
http://docs.appgyver.com/tooling/build-service/plugins/configuring-custom-plugins/
