### ISSUE TITLE
Getting issue during compile in ios 

### ISSUE THREAD

**Issue by Rajnishkumar184** [bit6/bit6-cordova#7]
Plugins/com.bit6.sdk/libPhoneRTC.a, missing required architecture x86_64 in file /Users/rajnishkumar/Documents/MYPROJECTS/demo/platforms/ios/demo/Plugins/com.bit6.sdk/libPhoneRTC.a (2 slices)

**Comment by Moussawi7** [comment]
Same issue here,
@Rajnishkumar184 Did you solve the issue?.
Thank you.

**Comment by narek-h** [comment]
Hello, 

please build/run with  --device flag  "cordova run ios --device"

**Comment by Moussawi7** [comment]
@narek-h Thanks a lot, your solution solve the issue.
