### ISSUE TITLE
Android marshmallow no outgoing voice

### ISSUE THREAD

**Issue by ghost** [bit6/bit6-cordova#8]
In android marshmallow voice is not reaching to other person, any solution?

**Comment by nmolinaca** [comment]
Same here voice is not reaching to other person. did you get the solution??

**Comment by sympaticus** [comment]
Also, I have encountered the same issue after upgrading my Android OS.
Did you find a solution?.
Thank you.

**Comment by narek-h** [comment]
Hello, 

could you please try enable all the required permissions from Settings->Apps->'YourApp'->Permissions. 

Please let me know if this fixes the issue. 

 Thanks,
    Narek

**Comment by Moussawi7** [comment]
Hello @narek-h ,
Thank you for your reply.
you are absolutely right, the permissions was disabled by default and i was not asking to grant these permissions anyway it's working now.
Does I need to install third party plugin to ask users for permissions?
Thank you.

**Comment by narek-h** [comment]
hi @Moussawi7, 

glad to hear it helped. 
Actually, at this moment our plugin/demo does not ask for permissions runtime. It's in our TODO to add that part sometime in coming releases but at this moment it's missing. 

Adding that part using third party plugins can resolve these issues. For instance before using specific feature ask to grant the needed permission. 

 Narek
