### ISSUE TITLE
Ringtone sound when incomming call

### ISSUE THREAD

**Issue by nmolinaca** [bit6/bit6-cordova#9]
When the app receives an incomming call notification the app sounds the default sound not the ringtone.

I was searching for solution and the solution is at your server, just adding to the GCM JSON "sound":"ringtone"

Example:

{
    "registration_ids": ["my device id"],
    "data": {
        "title": "Ringtone",
        "message": "Plays default ringtone sound",
        "soundname": "ringtone"
    }
}

Documentation: 
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#sound

**Comment by narek-h** [comment]
Thanks for the suggested solution. 

Actually this is in our TODO list, and hopefully will be fixed soon.
